
try:
    print(a)
except:
    print("exception")